### ISSUE TITLE
try to deploy any of the existing RHOAR Java boosters

### ISSUE THREAD

**Issue by helio-frota** [bucharest-gold/entente#183]
When using nodeshift with: `Windows10 + docker for windows [edge] + Hyper-V`
permissions-related errors appear:
```console
PS C:\Users\hf\Desktop\mean-booster> npm run openshift

> mean-booster@1.0.0 openshift C:\Users\hf\Desktop\mean-booster
> nodeshift --osc.strictSSL=false

2017-12-15T12:19:46.196Z INFO loading configuration
2017-12-15T12:19:46.220Z INFO using namespace myproject at https://192.168.1.6:8443
2017-12-15T12:19:46.228Z INFO creating archive of package.json, README.md, server.js, app
2017-12-15T12:19:46.277Z INFO creating build configuration mean-booster-s2i
2017-12-15T12:19:46.426Z INFO creating image stream mean-booster
2017-12-15T12:19:46.444Z INFO uploading binary archive C:\Users\hf\Desktop\mean-booster/tmp/nodeshift/build/archive.tar
2017-12-15T12:21:21.618Z INFO binary upload complete
2017-12-15T12:21:21.623Z INFO waiting for build to finish
2017-12-15T12:21:21.656Z TRACE Receiving source from STDIN as archive ...
2017-12-15T12:21:21.697Z TRACE ---> Installing application source
2017-12-15T12:21:21.699Z TRACE cp: cannot stat '/tmp/src/./app/resources': Permission denied
2017-12-15T12:21:21.699Z TRACE cp: cannot stat '/tmp/src/./app/controllers': Permission denied
2017-12-15T12:21:21.699Z TRACE cp: cannot stat '/tmp/src/./app/static': Permission denied
2017-12-15T12:21:21.700Z TRACE cp: cannot stat '/tmp/src/./app/model': Permission denied
2017-12-15T12:21:21.700Z TRACE error: build error: non-zero (13) exit code from bucharestgold/centos7-s2i-nodejs:latest
2017-12-15T12:21:22.111Z ERROR build failed with message: Assemble script failed.
2017-12-15T12:21:22.112Z ERROR Error: Assemble script failed. Error: Assemble script failed.
    at module.exports (C:\Users\hf\Desktop\mean-booster\node_modules\nodeshift\lib\binary-build.js:40:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mean-booster@1.0.0 openshift: `nodeshift --osc.strictSSL=false`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mean-booster@1.0.0 openshift script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hf\AppData\Roaming\npm-cache\_logs\2017-12-15T12_21_22_136Z-debug.log
```

so this issue is to check if the same happen with java boosters.

**Comment by helio-frota** [comment]
deploy java booster is working :
```
[INFO]
[INFO] <<< fabric8-maven-plugin:3.5.30:deploy (default-cli) < install @ wfswarm-rest-http <<<
[INFO]
[INFO]
[INFO] --- fabric8-maven-plugin:3.5.30:deploy (default-cli) @ wfswarm-rest-http ---
[INFO] F8: Using OpenShift at https://192.168.1.6:8443/ in namespace myproject with manifest C:\Users\hf\Desktop\wfswarm-rest-http\target\classes\META-INF\fabric8\openshift.yml
[INFO] OpenShift platform detected
[INFO] Using project: myproject
[INFO] Creating a Service from openshift.yml namespace myproject name wfswarm-rest-http
[INFO] Created Service: \target\fabric8\applyJson\myproject\service-wfswarm-rest-http.json
[INFO] Using project: myproject
[INFO] Creating a DeploymentConfig from openshift.yml namespace myproject name wfswarm-rest-http
[INFO] Created DeploymentConfig: \target\fabric8\applyJson\myproject\deploymentconfig-wfswarm-rest-http.json
[INFO] Creating Route myproject:wfswarm-rest-http host: null
[INFO] F8: HINT: Use the command `oc get pods -w` to watch your pods start up
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 08:01 min
[INFO] Finished at: 2017-12-15T15:59:03Z
[INFO] Final Memory: 68M/562M
[INFO] ------------------------------------------------------------------------
```
![aaa](https://user-images.githubusercontent.com/6443576/34052929-5a56435c-e1bc-11e7-9bc5-3ed078ed0642.PNG)

**Comment by lance** [comment]
Hmm, so the failure message says the assemble script is failing. Do you think [this](https://github.com/bucharest-gold/centos7-s2i-nodejs/blob/master/s2i/assemble#L6) might be the culprit?

**Comment by helio-frota** [comment]
I don't think the problem is the image because when using `oc` command it works.
screenshots here:
https://github.com/bucharest-gold/mean-booster/issues/22#issuecomment-349074559

But, I'm not 100% sure

**Comment by helio-frota** [comment]
related with: https://github.com/bucharest-gold/mean-booster/issues/22

**Comment by helio-frota** [comment]
working after override `s2i/bin/assemble` and `chmod 775 -R /tmp/src/.`
https://github.com/bucharest-gold/mean-booster/blob/master/.s2i/bin/assemble#L5-L6

https://github.com/bucharest-gold/mean-booster/issues/22#issuecomment-358160415
